### PR TITLE
website interface

### PR DESCRIPTION
**Pull request by agski**

### CODE REVIEW

**Comment by przxmek** [comment]
On second thought, maybe it would be better to have this endpoint like it used to be?
```
PUT /account
{
  "searchType": SearchType,
  "tabCompletion": boolean,
  "facebook_dropdown": boolean,
  "zendesk_dropdown": boolean,
  "menu_everywhere": boolean
}
```
and if one of the properties is missing/null - skip it.

This is the behavior I fixed in the https://github.com/PointMail/api-autocomplete/pull/123 (doesn't include new preference updates).

**Comment by agski** [comment]
@przxmek I dislike having to send back the entire Preference object on a single field update - passing around irrelevant info only makes it more confusing and cumbersome. What's the benefit of the full object approach instead of field, newVal?

**Comment by przxmek** [comment]
@agski sending single field in PUT /account is not restful, I wanted to make it consistent with the rules. I actually didn't want to send full object. I wanted to only send changed fields. But in one request that is updating the **Account** resource (PUT /account should do exactly this thing). 

The idea was like this:
```json
PUT /account
{
  "searchType": "hybdrid",
  "tabCompletion": false
}
```
would update only `searchType` & `tabCompletion`.

```json
PUT /account
{
  "zendesk_dropdown": true,
}
```
would update only `zendesk_dropdown`. This is how this endpoint used to work.

IMHO this is the most straightforward and the simplest solution as you expect PUT /account to modify **Account** resource and these are **Account** properties. It also comes with a very clear type definitions which makes it easier to use the endpoint.

`{field, newVal}` endpoint is extremely hard form type definitions. We can easily define allowed values for `field` - but allowed values for `newVal` depend on the `field`, so it gets complicated how to clearly define them. For example how do we send boolean data, do we convert it to string or do we keep them booleans - that's what was failing in backend tests. Other smaller disadvantage is that it's not RESTful.

**Comment by przxmek** [comment]
We need to rebase it on `dev` branch and it's good to go then.

**Comment by agski** [comment]
@przxmek I see your explanation makes sense - when we revisit this endpt I'll make the restful changes

**Pull request merged**
